/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewWindows;

import controller.UserController;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raposo
 */
public class menuManagerUserOptions extends javax.swing.JFrame {
    
    private UserController userController_ = new UserController();
    /**
     * Creates new form menuUserOptions
     */
    public menuManagerUserOptions() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        putUsersBtt = new javax.swing.JButton();
        getUsersBtt = new javax.swing.JButton();
        deleteUsersBtt = new javax.swing.JButton();
        backToMenuBtt = new javax.swing.JButton();
        deleteUserLabel = new javax.swing.JLabel();
        deleteUserField = new javax.swing.JTextField();
        deleteUserBtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Selecione uma opção");

        putUsersBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        putUsersBtt.setText("Atualizar dados de usuário");
        putUsersBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                putUsersBttMouseClicked(evt);
            }
        });
        putUsersBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putUsersBttActionPerformed(evt);
            }
        });

        getUsersBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getUsersBtt.setText("Ver Lista de usuários");
        getUsersBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getUsersBttMouseClicked(evt);
            }
        });

        deleteUsersBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteUsersBtt.setText("Deletar usuário");
        deleteUsersBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUsersBttMouseClicked(evt);
            }
        });
        deleteUsersBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUsersBttActionPerformed(evt);
            }
        });

        backToMenuBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backToMenuBtt.setText("Voltar");
        backToMenuBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMenuBttMouseClicked(evt);
            }
        });
        backToMenuBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuBttActionPerformed(evt);
            }
        });

        deleteUserLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        deleteUserLabel.setText("Informe o ID");

        deleteUserBtt.setText("Deletar");
        deleteUserBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserBttMouseClicked(evt);
            }
        });
        deleteUserBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backToMenuBtt)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getUsersBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(deleteUserLabel)
                                    .addGap(26, 26, 26)
                                    .addComponent(deleteUserField))
                                .addComponent(putUsersBtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteUsersBtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteUserBtt)
                        .addGap(257, 257, 257))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(getUsersBtt)
                .addGap(50, 50, 50)
                .addComponent(putUsersBtt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(deleteUsersBtt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteUserLabel)
                    .addComponent(deleteUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteUserBtt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backToMenuBtt)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void putUsersBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putUsersBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_putUsersBttActionPerformed

    private void backToMenuBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToMenuBttActionPerformed

    private void deleteUserBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserBttActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        deleteUserBtt.setVisible(false);
        deleteUserField.setVisible(false);
        deleteUserLabel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void deleteUsersBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUsersBttMouseClicked
        deleteUserBtt.setVisible(true);
        deleteUserField.setVisible(true);
        deleteUserLabel.setVisible(true);
    }//GEN-LAST:event_deleteUsersBttMouseClicked

    private void backToMenuBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMenuBttMouseClicked
        menuManagerOptions menu = new menuManagerOptions();
        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToMenuBttMouseClicked

    private void getUsersBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getUsersBttMouseClicked
        getUsers getusers = new getUsers();
        
        getusers.setVisible(true);
        
    }//GEN-LAST:event_getUsersBttMouseClicked

    private void putUsersBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_putUsersBttMouseClicked
        putUserMenu menu = new putUserMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_putUsersBttMouseClicked

    private void deleteUsersBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUsersBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUsersBttActionPerformed

    private void deleteUserBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserBttMouseClicked
        if(deleteUserField.getText()==null){
            JOptionPane.showMessageDialog(this, "O campo de ID precisa estar preenchido.");
        }else{
            try {
                int id = parseInt(deleteUserField.getText());

                userController_.deleteUser(id);
                JOptionPane.showMessageDialog(this, "Usuário deletado com sucesso.");
            } catch (SQLException ex) {
                Logger.getLogger(menuManagerUserOptions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteUserBttMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuManagerUserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuManagerUserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuManagerUserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuManagerUserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuManagerUserOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuBtt;
    private javax.swing.JButton deleteUserBtt;
    private javax.swing.JTextField deleteUserField;
    private javax.swing.JLabel deleteUserLabel;
    private javax.swing.JButton deleteUsersBtt;
    private javax.swing.JButton getUsersBtt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton putUsersBtt;
    // End of variables declaration//GEN-END:variables
}
