/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewWindows;

/**
 *
 * @author raposo
 */
public class menuManagerOptions extends javax.swing.JFrame {

    /**
     * Creates new form menuProducts
     */
    public menuManagerOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backToLoginBtt = new javax.swing.JButton();
        productsMenuBtt = new javax.swing.JButton();
        usersMenuBtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Selecione uma opção");

        backToLoginBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backToLoginBtt.setText("Voltar");
        backToLoginBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToLoginBttMouseClicked(evt);
            }
        });
        backToLoginBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginBttActionPerformed(evt);
            }
        });

        productsMenuBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productsMenuBtt.setText("Produtos");
        productsMenuBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsMenuBttMouseClicked(evt);
            }
        });
        productsMenuBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsMenuBttActionPerformed(evt);
            }
        });

        usersMenuBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usersMenuBtt.setText("Usuários");
        usersMenuBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMenuBttMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backToLoginBtt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(productsMenuBtt, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(usersMenuBtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(89, 89, 89)
                .addComponent(productsMenuBtt)
                .addGap(53, 53, 53)
                .addComponent(usersMenuBtt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(backToLoginBtt)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToLoginBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToLoginBttActionPerformed

    private void productsMenuBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsMenuBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsMenuBttActionPerformed

    private void productsMenuBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsMenuBttMouseClicked
        menuManagerProductsOptions menu = new menuManagerProductsOptions();
        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productsMenuBttMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void backToLoginBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginBttMouseClicked
        Window login = new Window();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToLoginBttMouseClicked

    private void usersMenuBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMenuBttMouseClicked
        menuManagerUserOptions menu = new menuManagerUserOptions();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usersMenuBttMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuManagerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuManagerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuManagerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuManagerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuManagerOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToLoginBtt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton productsMenuBtt;
    private javax.swing.JButton usersMenuBtt;
    // End of variables declaration//GEN-END:variables
}
