/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewWindows;

import controller.ProductController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raposo
 */
public class menuManagerProductsOptions extends javax.swing.JFrame {

    /**
     * Creates new form menuUserOptions
     */
    public menuManagerProductsOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        postProductBtt = new javax.swing.JButton();
        deleteProductBtt = new javax.swing.JButton();
        putProductBtt = new javax.swing.JButton();
        getProductBtt = new javax.swing.JButton();
        backToMenuBtt = new javax.swing.JButton();
        postNameLabel = new javax.swing.JLabel();
        postStockLabel = new javax.swing.JLabel();
        newProductName = new javax.swing.JTextField();
        newProductStock = new javax.swing.JTextField();
        postProduct = new javax.swing.JButton();
        deleteProductLabel = new javax.swing.JLabel();
        deleteProduct = new javax.swing.JButton();
        deleteProductField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Selecione uma opção");

        postProductBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        postProductBtt.setText("Inserir novo produto");
        postProductBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postProductBttMouseClicked(evt);
            }
        });
        postProductBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postProductBttActionPerformed(evt);
            }
        });

        deleteProductBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteProductBtt.setText("Deletar produto");
        deleteProductBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteProductBttMouseClicked(evt);
            }
        });
        deleteProductBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductBttActionPerformed(evt);
            }
        });

        putProductBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        putProductBtt.setText("Atualizar produto");
        putProductBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                putProductBttMouseClicked(evt);
            }
        });

        getProductBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getProductBtt.setText("Ver lista de produtos");
        getProductBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getProductBttMouseClicked(evt);
            }
        });

        backToMenuBtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backToMenuBtt.setText("Voltar");
        backToMenuBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMenuBttMouseClicked(evt);
            }
        });

        postNameLabel.setText("Nome");

        postStockLabel.setText("Quantidade");

        postProduct.setText("Confirm");
        postProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postProductMouseClicked(evt);
            }
        });
        postProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postProductActionPerformed(evt);
            }
        });

        deleteProductLabel.setText("ID");

        deleteProduct.setText("Confirm");
        deleteProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(putProductBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getProductBtt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(deleteProductBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteProductLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(postProductBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(postNameLabel)
                                            .addComponent(postStockLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deleteProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newProductStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postProduct)
                    .addComponent(backToMenuBtt)
                    .addComponent(deleteProduct))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(postProductBtt)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteProductBtt)
                    .addComponent(deleteProductLabel)
                    .addComponent(deleteProduct)
                    .addComponent(deleteProductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(putProductBtt)
                .addGap(46, 46, 46)
                .addComponent(getProductBtt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(backToMenuBtt)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postNameLabel)
                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postStockLabel)
                    .addComponent(newProductStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postProductBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postProductBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postProductBttActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        newProductName.setVisible(false);
        postNameLabel.setVisible(false);
        postStockLabel.setVisible(false);
        newProductStock.setVisible(false);
        postProduct.setVisible(false);
        deleteProduct.setVisible(false);
        deleteProductField.setVisible(false);
        deleteProductLabel.setVisible(false);
        deleteProduct.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void postProductBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postProductBttMouseClicked
        newProductName.setVisible(true);
        postNameLabel.setVisible(true);
        postStockLabel.setVisible(true);
        newProductStock.setVisible(true);
        postProduct.setVisible(true);
        deleteProduct.setVisible(false);
        deleteProductField.setVisible(false);
        deleteProductLabel.setVisible(false);
        deleteProduct.setVisible(false);
    }//GEN-LAST:event_postProductBttMouseClicked

    private void deleteProductBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductBttMouseClicked
        newProductName.setVisible(false);
        postNameLabel.setVisible(false);
        postStockLabel.setVisible(false);
        newProductStock.setVisible(false);
        postProduct.setVisible(false);
        deleteProduct.setVisible(true);
        deleteProductField.setVisible(true);
        deleteProductLabel.setVisible(true);
        deleteProduct.setVisible(true);
    }//GEN-LAST:event_deleteProductBttMouseClicked

    private void deleteProductBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProductBttActionPerformed

    private void postProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postProductActionPerformed

    private void deleteProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductMouseClicked
        try {
            ProductController productController = new ProductController();
            
            boolean verify = productController.deleteProduct(Integer.parseInt(deleteProductField.getText()));
            
            if(verify ==true)
                JOptionPane.showMessageDialog(this, "Produto excluído do estoque.");
            else
                JOptionPane.showMessageDialog(this, "Não existe usuário com esse Id.");
        } catch (SQLException ex) {
            Logger.getLogger(menuManagerProductsOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteProductMouseClicked

    private void postProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postProductMouseClicked
        ProductController productController = new ProductController();
        if(newProductName.getText()==null || newProductStock.getText()==null)
            JOptionPane.showMessageDialog(this, "Você precisa inserir todos os dados.");
        else{
            try {
                productController.insertProduct(newProductName.getText(),Integer.parseInt(newProductStock.getText()));      
                JOptionPane.showMessageDialog(this, "Produto adicionado ao estoque.");
            } catch (SQLException ex) {
                Logger.getLogger(menuManagerProductsOptions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_postProductMouseClicked

    private void putProductBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_putProductBttMouseClicked
        putProductMenu putWindow = new putProductMenu();
        
        putWindow.setVisible(true);
    }//GEN-LAST:event_putProductBttMouseClicked

    private void backToMenuBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMenuBttMouseClicked
        menuManagerOptions menu = new menuManagerOptions();
        
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToMenuBttMouseClicked

    private void getProductBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getProductBttMouseClicked
        getProducts getproducts = new getProducts();
        getproducts.setVisible(true);
    }//GEN-LAST:event_getProductBttMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuManagerProductsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuManagerProductsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuManagerProductsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuManagerProductsOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuManagerProductsOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuBtt;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JButton deleteProductBtt;
    private javax.swing.JTextField deleteProductField;
    private javax.swing.JLabel deleteProductLabel;
    private javax.swing.JButton getProductBtt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField newProductName;
    private javax.swing.JTextField newProductStock;
    private javax.swing.JLabel postNameLabel;
    private javax.swing.JButton postProduct;
    private javax.swing.JButton postProductBtt;
    private javax.swing.JLabel postStockLabel;
    private javax.swing.JButton putProductBtt;
    // End of variables declaration//GEN-END:variables
}
